version: '3'
name: dora-services
services:
  dora-mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql # Add mapping to store DB files on permanent storage
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: experiment
    labels:
      kompose.service.type: nodeport

  dora-backend:
    image: docker.io/library/dora-backend:latest
    ports:
      - "30080:8000"
    restart: "always"
    environment:
      FLASK_PORT: 5000
      TOP_K_DOCUMENTS: 10
      MINIMUM_ACCURACY: 0.50
      FETCH_K_DOCUMENTS: 100
      LAMBDA_MULT: 0.2
      STRATEGY: mmr
      CHAT_HISTORY_CONNECTION_STRING: ${MARIADB_INSTANCE_URL}/experiment
      FINAL_ANSWER_CONNECTION_STRING: ${MARIADB_INSTANCE_URL}/experiment
      FLASK_APP: ./app.py
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
    volumes:
      - ~/dora-logs/dora-backend:/app/logs
      # - chat_model_folder_path:/models/chat_models
      # - embedding_model_folder_path:/models/embedding_models
    depends_on:
      - dora-mariadb
    labels:
      kompose.service.type: nodeport
      kompose.volume.type: hostPath
      kompose.image-pull-policy: "Never"
volumes:
  mariadb-data:

