name: dora-services
networks:
  net:
    driver: bridge

services:
  dora-chromadb:
    image: chromadb/chroma:latest
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      IS_PERSISTENT: "TRUE"
      PERSIST_DIRECTORY: ${CHROMA_DB_PERSIST_DIR}
      ANONYMIZED_TELEMETRY: ${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    networks:
      - net
  dora-mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql # Add mapping to store DB files on permanent storage
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: experiment
    labels:
      kompose.service.type: nodeport
      kompose.volume.type: hostPath

  dora-backend:
    image: docker.io/library/dora-backend:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 30080:8000
    restart: "always"
    environment:
      FLASK_PORT: ${FLASK_PORT:?error}
      TOP_K_DOCUMENTS: ${TOP_K_DOCUMENTS:?error}
      MINIMUM_ACCURACY: ${MINIMUM_ACCURACY:?error}
      FETCH_K_DOCUMENTS: ${FETCH_K_DOCUMENTS:?error}
      LAMBDA_MULT: ${LAMBDA_MULT:?error}
      STRATEGY: ${STRATEGY:?error}
      CHAT_HISTORY_CONNECTION_STRING: ${MARIADB_INSTANCE_URL:?error}/experiment
      FINAL_ANSWER_CONNECTION_STRING: ${MARIADB_INSTANCE_URL:?error}/experiment
      FLASK_APP: ./app.py
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      LOGGING_FILE_DIR: /app/logs
    volumes:
      - logging_file_dir:/app/logs
      - ${CHAT_MODEL_FOLDER_PATH:?error:/models/chat_models
      - ${SENTENCE_TRANSFORMERS_HOME:?error}:/models/embedding_models
    depends_on:
      - dora-mariadb
    labels:
      kompose.service.type: nodeport
      kompose.volume.type: hostPath
      kompose.image-pull-policy: "Never"

volumes:
  logging_file_dir:
  mariadb_data:
  chromadb_data:


