name: docker-pipeline
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HTTP_PROXY: "http://134.209.28.98:3128"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: dora-backend:latest
          build-args: |
            HTTP_PROXY=$HTTP_PROXY
            HTTPS_PROXY=$HTTP_PROXY
          outputs: type=docker, dest=/tmp/dora-backend.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dora-backend
          path: /tmp/dora-backend.tar

  compose:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Show HTTP_PROXY
        run: echo $HTTP_PROXY
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dora-backend
          path: /tmp
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Load image
        run: |
          docker load --input /tmp/dora-backend.tar
          docker image ls -a
      - name: Run Docker Compose
        run: |
          docker-compose up -d
      - name: Display Running Containers
        run: |
          docker ps -a
      - name: Stop Docker Compose
        run: |
          docker-compose down


      
